# Site settings
title:   Brian Reichholf
locale:  en_GB
url:     "https://blog.reichholf.me"
# email:   brian.reichholf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog on bioinformatics, python coding, RNA data analysis and the chronicles
  of a PhD student.
baseurl: "" # the subpath of your site, e.g. /blog/

# Jekyll configuration
permalink:   pretty
markdown:    kramdown
# markdown:    redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji

jekyll-mentions:
  base_url: https://twitter.com

# redcarpet:
#   extensions: ['smart', 'no_intra_emphesis', 'tables', 'fenced-code-blocks', 'autolink', 'strikethrough', 'superscript', 'highlight', 'footnotes', 'underline', 'with_toc_data']

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Brian Reichholf
  avatar: bio-profile.svg
  bio: "Molecular Biologist by day, electrical engineer by night, and bioinformatician somewhere inbetween."
  email: brian.reichholf@gmail.com
  disqus-shortname:
  twitter: breichholf #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: breichholf #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: brianreichholf #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md","CNAME"]

# Build command options
# lsi: TRUE

# Front matter defaults:
defaults:
  -
    scope:
      path: ""
    values:
      author: "brian"
      share: false
