# Site settings
name:   Brian Reichholf
locale:  en_GB
url:     "https://www.reichholf.me"
description: > # this means to ignore newlines
  A blog on bioinformatics, python and R coding, RNA data analysis and the chronicles of a PhD student.

author_name:  Brian Reichholf
author_image: /images/bio-profile.svg
author_job: Molecular Biologist/Bioinformatician
author_bio: >
  Molecular Biologist by day, electrical engineer by night, and bioinformatician somewhere inbetween.

github_url:   "https://github.com/breichholf"
twitter_url:  "https://twitter.com/breichholf"
linkedin_url: "https://linkedin.com/in/brianreichholf"
feed_url:     "https://feedburner.google.com/breichholf"
so_url: https://stackoverflow.com/users/3045544/brian

kramdown:
  auto_ids: true
  footnote_nr: 1
  parse_block_html: true
  #  smart_quotes: apos,apos,quot,quot

permalink: /blog/:year/:month/:day/:title/

timezone: Europe/Vienna
